apiVersion: apps/v1
kind: Deployment
metadata:
  name:dfjleio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfjleio
  template:
    metadata:
      labels:
        app: dfjleio
    spec:
      containers:
      - image: okteto.dev/dfjleio:latest
        name: dfjleio
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9a4826cd-d9b6-4679-a97c-eff8041b9f83"
        - name: Vless_Path
          value: "/vlnjkd434"
        - name: Vmess_UUID
          value: "9a4826cd-d9b6-4679-a97c-eff8041b9f83"
        - name: Vmess_Path
          value: "/vmhekje554"
        - name: Share_Path
          value: "/v2link"
